//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toDoList.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class toDoList
    {
        public int toDoListID { get; set; }
        public string Name { get; set; }
    }
}
