//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toDoList.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int usersID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string hashedPassword { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    }
}
